### ISSUE TITLE
Find & implement good hash function for hash partitioning

### ISSUE THREAD

**Issue by NHoff95** [NHoff95/hyrise#15]
In hash_function.cpp, the calculate_hash(const AllTypeVariant value_to_hash) function must be implemented to get a useful hash partitioning.

**Comment by jchromik** [comment]
Implemented using `std::hash`.
Moved to `src/lib/storage/partitioning`.
Renamed `calculate_hash` to `operator()`.

See #30 and commit `3a348444c64566baa06cd83b16496092183783df`.
